blog/app.py
from flask import Flask, render_template

from blog.articles.articles import articles
from blog.index.index import index
from blog.user.users import user


# app = Flask(__name__)
#
#
# @app.route('/')
# def index():
#     return render_template('index.html')


#
# app.register_blueprint(user, url_prefix='/users')

def create_app() -> Flask:
    app = Flask(__name__)
    register_blueprint(app)
    return app


def register_blueprint(app: Flask):
    app.register_blueprint(user)
    app.register_blueprint(index)
    app.register_blueprint(articles)

blog/views/users.py
from flask import Blueprint, render_template
from werkzeug.exceptions import NotFound

user = Blueprint('user', __name__)
USERS = {
    1: 'ALEX',
    2: 'NATALI',
    3: 'PITER',
}


@user.route('/')
def user_list():
    return render_template('user/list.html', users=USERS)


@user.route("/<int:user_id>/")
def user_details(user_id: int):
    try:
        user_name = USERS[user_id]
    except KeyError:
        raise NotFound(f"User #{user_id} doesn't exist!")
    return render_template('user/datails.html', user_id=user_id,
                           user_name=user_name)

blog/templates/articles/article_detalis.html
{% extends 'base.html'%}

{% block title %}
Article{{artik_id}}
{% endblock %}

{% block body %}
<h1>{{artik_name['test']}} автор {{ authors[artik_name['author']]}}</h1>
{% endblock %}

blog/templates/articles/article_list.html
{% extends 'base.html'%}

{% block title %}
article list
{% endblock %}

{% block body %}
<h1>article</h1>
<ul>
    {%for artik_id in articles%}
    <li><a href="{{ url_for('articles.articles_details', pk=artik_id)}}">{{ articles[artik_id]['test']}}</a></li>
    {% endfor %}
</ul>

{% endblock %}

blog/templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    {% block css %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    {% endblock %}

    <title>
        {% block title %}
        Title
        {% endblock %}
    </title>
</head>
<body>

<div class="container ">
    <div class="row">
        <div class="col">
            {% include 'navbar.html'%}
            {% block body %}
            Title
            {% endblock %}
            {% block js %}
        </div>
    </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
{% endblock %}
</body>
</html>

blog/templates/index/index.html
{% extends 'base.html'%}

{% block title %}
        index page
{% endblock %}

{% block body %}
    <h1>Hello im hear</h1>
{% endblock %}

blog/templates/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
        <a class="navbar-brand" href="{{ url_for('index.index_1')}}">Navbar</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{{ url_for('user.user_list')}}">Authors</a>
        </li>
        <li class=" nav-item">
                    <a class="nav-link" href="{{ url_for('articles.articles_list')}}">articles</a>
        </li>
      </ul>
        </div>
    </div>
</nav>

blog/templates/user/datails.html
{% extends 'base.html'%}

{% block title %}
        User{{user_id}}
{% endblock %}

{% block body %}
    <h1>{{user_name}}</h1>
{% endblock %}

blog/templates/user/list.html
{% extends 'base.html'%}

{% block title %}
    User list
{% endblock %}

{% block body %}
    <h1>Users</h1>
<ul>
    {%for user_id in users%}
    <li><a href="{{ url_for('user.user_details', pk=user_id)}}">{{ users[user_id] }}</a> </li>
    {% endfor %}
</ul>

{% endblock %}